name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  TESTCMD: java -cp "jvm/target/scala-2.13/*:jvm/target/scala-2.13/apexls_2.13-*.jar" com.nawforce.apexlink.ApexLink -verbose -nocache -outlinemulti  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: olafurpg/setup-scala@v11

    - name: Checkout samples repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
        repository: apex-dev-tools/apex-samples
        path: samples

    - name: Build
      run: |
        sbt build package test

    - name: TriggerX
      run: ${{env.TESTCMD}} samples/TriggerX/TriggerX

    - name: apex-query-builder 
      run: ${{env.TESTCMD}} samples/apex-query-builder/apex-query-builder

    - name: salesforce-bot-toolkit 
      run: ${{env.TESTCMD}} samples/salesforce-bot-toolkit/salesforce-bot-toolkit

    - name: SalesforceDurableStreamingDemo 
      run: ${{env.TESTCMD}} samples/SalesforceDurableStreamingDemo/SalesforceDurableStreamingDemo

    - name: amoss 
      run: ${{env.TESTCMD}} samples/amoss/amoss

    - name: SimpleLightningComponents
      run: ${{env.TESTCMD}} samples/SimpleLightningComponents/SimpleLightningComponents

    # Unreachable statement, throw + return
    #- name: FormulaShare-DX 
    #  run: ${{env.TESTCMD}} samples/FormulaShare-DX/FormulaShare-DX

    - name: Apex-for-Xero 
      run: ${{env.TESTCMD}} samples/Apex-for-Xero/Apex-for-Xero

    - name: sendgrid-apex 
      run: ${{env.TESTCMD}} samples/sendgrid-apex/sendgrid-apex

    # Project can't be deployed needs to be removed
    #- name: FindNearby
    #  run: ${{env.TESTCMD}} samples/FindNearby

    # No matching method found for 'getAsyncApexJobResult' on 'System.FinalizerContext'.
    # This project cannot be pushed.
    #- name: promiseV3 
    #  run: java -cp "apexlink/target/dependency/*:apexlink/target/apexlink-1.4.2.jar" com.nawforce.apexlink.ApexLink -verbose -nocache -outlinemulti samples/promiseV3/promiseV3

    # https://github.com/financialforcedev/ff-apex-ls/issues/259
    # - name: Apex-Opensource-Library 
    #  run: ${{env.TESTCMD}} samples/Apex-Opensource-Library/Apex-Opensource-Library

    - name: SFDCRules 
      run: ${{env.TESTCMD}} samples/SFDCRules/SFDCRules

    - name: forcelog 
      run: ${{env.TESTCMD}} samples/forcelog/forcelog

    - name: Apex-XML-Serializer 
      run: ${{env.TESTCMD}} samples/Apex-XML-Serializer/Apex-XML-Serializer

    - name: ObjectMerge 
      run: ${{env.TESTCMD}} samples/ObjectMerge/ObjectMerge

    - name: grid 
      run: ${{env.TESTCMD}} samples/grid/grid

    # Unreachable statement, bad if/else logic
    #- name: soql-secure 
    #  run: ${{env.TESTCMD}} samples/soql-secure/soql-secure

    - name: box-salesforce-sdk 
      run: ${{env.TESTCMD}} samples/box-salesforce-sdk/box-salesforce-sdk

    - name: Angular 
      run: ${{env.TESTCMD}} samples/Angular/Angular

    - name: Lightweight-Trigger-Framework 
      run: ${{env.TESTCMD}} samples/Lightweight-Trigger-Framework/Lightweight-Trigger-Framework

    - name: SObjectFabricator 
      run: ${{env.TESTCMD}} samples/SObjectFabricator/SObjectFabricator

    - name: ApexTriggerHandler 
      run: ${{env.TESTCMD}} samples/ApexTriggerHandler/ApexTriggerHandler

    - name: forcedotcom-enterprise-architecture 
      run: ${{env.TESTCMD}} samples/forcedotcom-enterprise-architecture/forcedotcom-enterprise-architecture

    - name: sf-sandbox-post-copy 
      run: ${{env.TESTCMD}} samples/sf-sandbox-post-copy/sf-sandbox-post-copy

    - name: Multi-File-Uploader-Force 
      run: ${{env.TESTCMD}} samples/Multi-File-Uploader-Force/Multi-File-Uploader-Force

    - name: logger 
      run: ${{env.TESTCMD}} samples/logger/logger

    - name: apex-sobjectdataloader 
      run: ${{env.TESTCMD}} samples/apex-sobjectdataloader/apex-sobjectdataloader

    - name: q 
      run: ${{env.TESTCMD}} samples/q/q

    - name: MyTriggers 
      run: ${{env.TESTCMD}} samples/MyTriggers/MyTriggers

    - name: ForceDotComSprintWall 
      run: ${{env.TESTCMD}} samples/ForceDotComSprintWall/ForceDotComSprintWall

    - name: apex-rest-route 
      run: ${{env.TESTCMD}} samples/apex-rest-route/apex-rest-route

    - name: flowtoolbelt 
      run: ${{env.TESTCMD}} samples/flowtoolbelt/flowtoolbelt

    - name: user-access-visualization 
      run: ${{env.TESTCMD}} samples/user-access-visualization/user-access-visualization

    - name: einstein-ai 
      run: ${{env.TESTCMD}} samples/einstein-ai/einstein-ai

    # Duplicate type
    # - name: purealoe-lwc
    # run: ${{env.TESTCMD}} samples/purealoe-lwc

    - name: HyperBatch 
      run: ${{env.TESTCMD}} samples/HyperBatch

    # Missing class DmlWrapper
    # - name: Interactions-for-Student-Recruitment
    #  run: ${{env.TESTCMD}} samples/Interactions-for-Student-Recruitment

    - name: sobject-work-queue 
      run: ${{env.TESTCMD}} samples/sobject-work-queue/sobject-work-queue

    - name: ffhttp-core 
      run: ${{env.TESTCMD}} samples/ffhttp-core/ffhttp-core

    - name: Force.com-Toolkit-for-Facebook 
      run: ${{env.TESTCMD}} samples/Force.com-Toolkit-for-Facebook/Force.com-Toolkit-for-Facebook

    - name: sfdc-oauth-playground 
      run: ${{env.TESTCMD}} samples/sfdc-oauth-playground/sfdc-oauth-playground

    - name: salesforce-limit-monitor 
      run: ${{env.TESTCMD}} samples/salesforce-limit-monitor/salesforce-limit-monitor

    # Unreachable statement, throw + return
    #- name: Centralized-Salesforce-Dev-Framework
    #  run: ${{env.TESTCMD}} samples/Centralized-Salesforce-Dev-Framework/Centralized-Salesforce-Dev-Framework

    - name: eventlogging 
      run: ${{env.TESTCMD}} samples/eventlogging/eventlogging

    - name: quiz-host-app 
      run: ${{env.TESTCMD}} samples/quiz-host-app/quiz-host-app

    - name: sfdc-related-files-lightning 
      run: ${{env.TESTCMD}} samples/sfdc-related-files-lightning/sfdc-related-files-lightning

    - name: sObject-Remote 
      run: ${{env.TESTCMD}} samples/sObject-Remote/sObject-Remote

    - name: apex-domainbuilder 
      run: ${{env.TESTCMD}} samples/apex-domainbuilder/apex-domainbuilder

    - name: Force.com-Helper-Classes 
      run: ${{env.TESTCMD}} samples/Force.com-Helper-Classes/Force.com-Helper-Classes

    - name: selector 
      run: ${{env.TESTCMD}} samples/selector/selector

    - name: R-apex 
      run: ${{env.TESTCMD}} samples/R-apex/R-apex

    # https://github.com/financialforcedev/ff-apex-ls/issues/260 & https://github.com/financialforcedev/ff-apex-ls/issues/261
    #- name: rflib 
    #  run: ${{env.TESTCMD}} samples/rflib/rflib

    - name: apex-dml-manager 
      run: ${{env.TESTCMD}} samples/apex-dml-manager/apex-dml-manager

    - name: ConnectApiHelper 
      run: ${{env.TESTCMD}} samples/ConnectApiHelper/ConnectApiHelper

    - name: sfdc-convert-attachments-to-chatter-files 
      run: ${{env.TESTCMD}} samples/sfdc-convert-attachments-to-chatter-files/sfdc-convert-attachments-to-chatter-files

    - name: Forceea-data-factory 
      run: ${{env.TESTCMD}} samples/Forceea-data-factory/Forceea-data-factory/dx

    # project is valid and can be deployed with no modification. However, there seems to be an issues around finding types that needs more investigation
    # - name: ApexTestKit
    #  run: ${{env.TESTCMD}} samples/ApexTestKit/ApexTestKit

    - name: jsonparse 
      run: ${{env.TESTCMD}} samples/jsonparse/jsonparse

    - name: sirono-common 
      run: ${{env.TESTCMD}} samples/sirono-common/sirono-common

    - name: apex-trigger-actions-framework 
      run: ${{env.TESTCMD}} samples/apex-trigger-actions-framework/apex-trigger-actions-framework

    - name: esapi 
      run: ${{env.TESTCMD}} samples/esapi/esapi

    - name: EnhancedLightningGrid 
      run: ${{env.TESTCMD}} samples/EnhancedLightningGrid/EnhancedLightningGrid

    - name: processBuilderBlocks 
      run: ${{env.TESTCMD}} samples/processBuilderBlocks/processBuilderBlocks

    - name: promise 
      run: ${{env.TESTCMD}} samples/promise/promise

    - name: Query.apex 
      run: ${{env.TESTCMD}} samples/Query.apex/Query.apex

    - name: apex-unified-logging 
      run: ${{env.TESTCMD}} samples/apex-unified-logging/apex-unified-logging

    - name: Zippex 
      run: ${{env.TESTCMD}} samples/Zippex/Zippex

    - name: TestDataFactory 
      run: ${{env.TESTCMD}} samples/TestDataFactory/TestDataFactory

    - name: automation-components 
      run: ${{env.TESTCMD}} samples/automation-components/automation-components

    - name: force-di 
      run: ${{env.TESTCMD}} samples/force-di/force-di

    - name: EDA 
      run: ${{env.TESTCMD}} samples/EDA/EDA

    - name: apex-lambda 
      run: ${{env.TESTCMD}} samples/apex-lambda/apex-lambda

    - name: sfdx-mass-action-scheduler 
      run: ${{env.TESTCMD}} samples/sfdx-mass-action-scheduler/sfdx-mass-action-scheduler

    # https://github.com/financialforcedev/ff-apex-ls/issues/262
    # - name: apex-recipes
    #   run: ${{env.TESTCMD}} samples/apex-recipes/apex-recipes

    # Project not deployable as is. May need building for the errors to disappear
    # Error seems to be able to about no resolving a class
    #- name: NPSP 
    #  run: ${{env.TESTCMD}} samples/NPSP

    - name: apex-mdapi 
      run: ${{env.TESTCMD}} samples/apex-mdapi/apex-mdapi

    # Issue around apex-parser
    # https://github.com/financialforcedev/ff-apex-ls/issues/264
    # https://github.com/financialforcedev/ff-apex-ls/issues/265
    # - name: apex-rollup 
    #  run: ${{env.TESTCMD}} samples/apex-rollup/apex-rollup

    # Multiple issues for this project. One of them is
    # https://github.com/financialforcedev/ff-apex-ls/issues/267
    # https://github.com/financialforcedev/ff-apex-ls/issues/268
    # One more issue around not finding fields in custom SObjects that needs more investigation
    # - name: NebulaLogger
    #  run: ${{env.TESTCMD}} samples/NebulaLogger/NebulaLogger

    - name: apex-toolingapi 
      run: ${{env.TESTCMD}} samples/apex-toolingapi/apex-toolingapi

    - name: Automated-Testing-for-Force 
      run: ${{env.TESTCMD}} samples/Automated-Testing-for-Force/Automated-Testing-for-Force

    # Unreachable statement, throw + return
    #- name: CustomMetadataLoader
    #  run: ${{env.TESTCMD}} samples/CustomMetadataLoader/CustomMetadataLoader

    - name: declarative-lookup-rollup-summaries 
      run: ${{env.TESTCMD}} samples/declarative-lookup-rollup-summaries/declarative-lookup-rollup-summaries

    - name: df12-apex-enterprise-patterns 
      run: ${{env.TESTCMD}} samples/df12-apex-enterprise-patterns/df12-apex-enterprise-patterns

    - name: df12-deployment-tools 
      run: ${{env.TESTCMD}} samples/df12-deployment-tools/df12-deployment-tools

    - name: dreamhouse-sfdx 
      run: ${{env.TESTCMD}} samples/dreamhouse-sfdx/dreamhouse-sfdx

    - name: fflib-apex-mocks 
      run: ${{env.TESTCMD}} samples/fflib-apex-mocks/fflib-apex-mocks

    - name: fflib-apex-common 
      run: |
        cp -r samples/fflib-apex-mocks/fflib-apex-mocks samples/fflib-apex-common
        ${{env.TESTCMD}} samples/fflib-apex-common

    - name: fflib-apex-common-samplecode 
      run: |
        cp -r samples/fflib-apex-mocks/fflib-apex-mocks samples/fflib-apex-common-samplecode
        cp -r samples/fflib-apex-common/fflib-apex-common samples/fflib-apex-common-samplecode
        ${{env.TESTCMD}} samples/fflib-apex-common-samplecode

    - name: at4dx 
      run: |
        cp -r samples/fflib-apex-mocks/fflib-apex-mocks samples/at4dx
        cp -r samples/fflib-apex-common/fflib-apex-common samples/at4dx
        cp -r samples/force-di/force-di samples/at4dx
        ${{env.TESTCMD}} samples/at4dx

    - name: HEDAP 
      run: ${{env.TESTCMD}} samples/HEDAP/HEDAP

    # Unreachable statement, bad if/else logic
    #- name: Milestones-PM
    #  run: ${{env.TESTCMD}} samples/Milestones-PM/Milestones-PM

    - name: Salesforce-Lookup-Rollup-Summaries 
      run: ${{env.TESTCMD}} samples/Salesforce-Lookup-Rollup-Summaries/Salesforce-Lookup-Rollup-Summaries

    - name: Salesforce-Test-Factory 
      run: ${{env.TESTCMD}} samples/Salesforce-Test-Factory/Salesforce-Test-Factory

    - name: sfdc-trigger-framework 
      run: ${{env.TESTCMD}} samples/sfdc-trigger-framework/sfdc-trigger-framework

    - name: SmartFactory-for-Force.com 
      run: ${{env.TESTCMD}} samples/SmartFactory-for-Force/SmartFactory-for-Force

    # Unreachable statement, double return
    #- name: twilio-salesforce
    #  run: ${{env.TESTCMD}} samples/twilio-salesforce/twilio-salesforce

    - name: Visualforce-Multiselect-Picklist 
      run: ${{env.TESTCMD}} samples/Visualforce-Multiselect-Picklist/Visualforce-Multiselect-Picklist

    - name: visualforce-table-grid 
      run: ${{env.TESTCMD}} samples/visualforce-table-grid/visualforce-table-grid

    - name: visualforce-typeahead 
      run: ${{env.TESTCMD}} samples/visualforce-typeahead/visualforce-typeahead

    # SObject issue could be related to https://github.com/financialforcedev/ff-apex-ls/issues/260
    # Errors around resolving a clas that's in an unpackaged folder that contains a package.xml
    # - name: Cumulus
    #  run: ${{env.TESTCMD}} samples/Cumulus

    - name: ActionPlansV4
      run: java -cp "apexlink/target/dependency/*:apexlink/target/apexlink.jar" com.nawforce.apexlink.ApexLink -verbose -nocache -outlinemulti samples/ActionPlansV4/ActionPlansV4

    - name: survey-force
      run: java -cp "apexlink/target/dependency/*:apexlink/target/apexlink.jar" com.nawforce.apexlink.ApexLink -verbose -nocache -outlinemulti samples/survey-force/survey-force


