name: Build

on:
  push:
    branches: [master, main]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "sbt"

      - uses: sbt/setup-sbt@v1


      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: |
            js/npm/package-lock.json
            mcp-npm/package-lock.json

      - name: FormatCheck
        run: sbt scalafmtCheck # Does not check test files currently

      - name: Build
        run: sbt build

      - name: Test
        run: sbt test

      - name: Build MCP Server (Regular)
        run: |
          cd mcp
          sbt test
          sbt buildRegular

      - name: Build MCP Server (Standalone)
        run: |
          cd mcp
          sbt buildStandalone

      - name: Build MCP NPM Package
        run: |
          cd mcp-npm
          npm ci
          npm run build
          npm run lint

      - name: Test MCP NPM Package
        run: |
          cd mcp-npm
          npm run test:unit

      - name: Checkout samples repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: apex-dev-tools/apex-samples
          path: apex-samples
          ref: v1.4.0

      - name: Set samples env
        run: echo "SAMPLES=$GITHUB_WORKSPACE/apex-samples" >> "$GITHUB_ENV"

      - name: System Test
        shell: 'script -q -e -c "bash {0}"' # Color support
        run: npm run test-samples
        working-directory: js/npm
