name: apexlink build and tests 

# Temp change to test reusable workflows

on:
  workflow_dispatch:

jobs:
  linux_build_java_8:
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      java_version: "8"    
      dependencies_name: "linux_java_8_deps"
      artifact_name: "linux_java_8"

  linux_test_java_8:
    needs: linux_build_java_8
    uses: ./.github/workflows/reusable_tests.yml
    with:
      agent: "ubuntu-latest"
      java_version: "8"    
      dependencies_name: "linux_java_8_deps"
      artifact_name: "linux_java_8"

  windows_build_java_8:
    uses: ./.github/workflows/reusable_windows_build.yml
    with:
      java_version: "8"    
      dependencies_name: "windows_java_8_deps"
      artifact_name: "windows_java_8"

  windows_test_java_8:
    needs: windows_build_java_8
    uses: ./.github/workflows/reusable_tests.yml
    with:
      agent: "ubuntu-latest"
      java_version: "8"    
      dependencies_name: "windows_java_8_deps"
      artifact_name: "windows_java_8"

