name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
        cache: "maven"

    - name: pkgforce-checkout
      uses: actions/checkout@v2
      with:
        repository: nawforce/pkgforce
        path: './pkgforce'

    - name: pkgforce-compile
      working-directory: './pkgforce'
      run: sbt pkgforceJVM/publishM2

    - name: runforce-checkout
      uses: actions/checkout@v2
      with:
        repository: nawforce/runforce
        path: './runforce'

    - name: runforce-compile
      working-directory: './runforce'
      run: mvn -B install -Dgpg.skip

    - name: Build with Maven
      run: |
        mvn --version
        mvn -B package
