name: Cross Platform Tests

# This script currently runs windows/linux builds and tests in parallel for
# java versions 8, 11, and 17.

on:
  workflow_dispatch:

jobs:
  cross_build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        java_version: [8, 11, 17]

    runs-on: ${{ matrix.os }}

    name: "Cross build - ${{ matrix.os }}, Java ${{ matrix.java_version }}"

    steps:
      - run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java_version }}

      - uses: sbt/setup-sbt@v1

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build
        run: sbt build

      - name: Test
        run: sbt test

      - name: Build MCP Server
        if: ${{ matrix.java_version >= 17 }}
        run: |
          cd mcp
          sbt test
          sbt buildRegular
