name: resuable windows build

on:
  workflow_dispatch:

  workflow_call:
    inputs:
      java_version: 
        description: 'Version of java'
        default: '8'
        required: false
        type: string
      dependencies_name:
        description: 'Name for dependencies artifact'
        default: 'dependencies'
        required: false
        type: string
      artifact_name:
        description: 'Name for apexlink artifact'
        default: 'artifact'
        required: false
        type: string

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10

    - name: Set up java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ inputs.java_version }}
        cache: "maven"
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.1

    - name: runforce-checkout
      uses: actions/checkout@v2
      with:
        repository: nawforce/runforce
        path: './runforce'

    - name: runforce-compile
      working-directory: './runforce'
      run: mvn -B install -D gpg.skip

    - name: Build with Maven
      run: |
        mvn --version
        mvn -B install -D gpg.skip

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.dependencies_name }}
        path: ./apexlink/target/dependency/
        retention-days: 1

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
        path: ./apexlink/target/apexlink.jar
        retention-days: 1

