name: UnitTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: |
            8
            17
          cache: "sbt"

      - uses: sbt/setup-sbt@v1

      - name: Set Java environment variables
        run: |
          echo "JAVA_HOME_8=$JAVA_HOME_8_X64" >> $GITHUB_ENV
          echo "JAVA_HOME_17=$JAVA_HOME_17_X64" >> $GITHUB_ENV

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: js/npm/package-lock.json

      - name: Build
        run: sbt build
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8 }}

      - name: Test
        run: sbt test
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8 }}
