name: UnitTest

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "sbt"

      - uses: sbt/setup-sbt@v1


      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: js/npm/package-lock.json

      - name: Build
        run: sbt build

      - name: Test
        run: sbt test
