name: WinBuild

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
        cache: "maven"

    - name: Build
      run: sbt build

    - name: Test
      run: sbt test
